# Generated by Django 5.2.1 on 2025-07-02 04:11

import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userdetials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetials',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetials',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=user_app.models.user_profile_picture_path),
        ),
    ]
